# Site settings
title: Tim Alonso's Blog
email: alonso2392@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timalonso.co.uk" # the base hostname & protocol for your site
twitter_username: TimAlonso
github_username:  TimAlonso

# Build settings
markdown: kramdown

sass_dir: /blog/_sass